// Floating GenAI billing assistant (Google Gemini, via the chatWithBot
// Cloud Function). Master-only: checks profiles/{uid}.role itself, since
// pages that include this script only redirect non-master users away from
// billing.html specifically, not from welcome/dashboard/profile.
//
// Icon behaviour (drag/edge-snap) matches the earlier WhatsApp launcher.
// On billing.html it drives the real invoice form via window.NKMWBillingBridge
// (defined inline in billing.html) so a bot-drafted invoice is generated by
// the exact same code path as a manually typed one. From any other page, a
// draft/generate request hands off to billing.html via sessionStorage.
(function () {
  var EDGE_MARGIN = 16;
  var DRAG_THRESHOLD = 6;
  var POSITION_KEY = "nkmw-bot-widget-pos";
  var STATE_KEY = "nkmw-bot-state"; // { messages: [{role,text,draft?}], open, lastDraft }
  var HANDOFF_KEY = "nkmw-bot-handoff"; // { draft, action } -- set right before navigating to billing.html

  var firebaseConfig = {
    apiKey: "AIzaSyDkEyDAOah5XzAOVjUux9SLhH60To2oTKs",
    authDomain: "new-kamal-metal-works.firebaseapp.com",
    projectId: "new-kamal-metal-works",
    storageBucket: "new-kamal-metal-works.firebasestorage.app",
    messagingSenderId: "595817400572",
    appId: "1:595817400572:web:8617eb7419e5049524af79"
  };

  function onBillingPage() {
    return /billing\.html/.test(window.location.pathname);
  }

  function loadState() {
    try {
      var raw = sessionStorage.getItem(STATE_KEY);
      if (raw) return JSON.parse(raw);
    } catch (err) { /* ignore */ }
    return { messages: [], open: false, lastDraft: null };
  }

  function injectStyles() {
    var style = document.createElement("style");
    style.textContent =
      ".bot-launcher {" +
      "  position: fixed; right: 16px; bottom: 16px; z-index: 999;" +
      "  opacity: 0; transform: translateY(8px); pointer-events: none;" +
      "  transition: opacity .3s var(--ease, ease), transform .3s var(--ease, ease);" +
      "  touch-action: none;" +
      "}" +
      ".bot-launcher.is-visible { opacity: 1; transform: translateY(0); pointer-events: auto; }" +
      ".bot-launcher.is-nudged { transform: translateY(var(--bot-nudge, 0px)); }" +
      ".bot-launcher.is-visible.is-nudged { transform: translateY(var(--bot-nudge, 0px)); }" +
      ".bot-launcher.is-dragging { transition: none; }" +
      ".bot-fab {" +
      "  width: 48px; height: 48px; border-radius: 50%; border: none; padding: 0;" +
      "  background: var(--surface, #fff);" +
      "  display: flex; align-items: center; justify-content: center;" +
      "  box-shadow: var(--shadow-md, 0 12px 32px rgba(0,0,0,0.2));" +
      "  transition: transform .25s var(--ease, ease), box-shadow .25s var(--ease, ease);" +
      "  cursor: grab;" +
      "}" +
      ".bot-launcher.is-dragging .bot-fab { cursor: grabbing; }" +
      ".bot-fab svg { width: 30px; height: 30px; }" +
      ".bot-fab:hover { transform: scale(1.06); }" +
      ".bot-panel {" +
      "  position: fixed; z-index: 1000; width: min(360px, calc(100vw - 32px));" +
      "  height: min(520px, calc(100vh - 100px)); background: var(--surface, #fff);" +
      "  border-radius: var(--radius-lg, 22px); box-shadow: var(--shadow-md, 0 12px 32px rgba(0,0,0,0.25));" +
      "  display: none; flex-direction: column; overflow: hidden; border: 1px solid var(--line, #ddd);" +
      "}" +
      ".bot-panel.is-open { display: flex; }" +
      ".bot-panel-head {" +
      "  display: flex; align-items: center; justify-content: space-between;" +
      "  padding: 14px 16px; border-bottom: 1px solid var(--line, #ddd);" +
      "  font-family: \"Space Grotesk\", sans-serif; font-weight: 600; color: var(--ink, #1D1D1F);" +
      "}" +
      ".bot-panel-close {" +
      "  background: none; border: none; font-size: 20px; line-height: 1; cursor: pointer;" +
      "  color: var(--ink-muted, #6E6E73); padding: 4px;" +
      "}" +
      ".bot-panel-body { flex: 1; overflow-y: auto; padding: 14px 16px; display: flex; flex-direction: column; gap: 10px; }" +
      ".bot-msg { max-width: 85%; padding: 9px 13px; border-radius: var(--radius, 14px); font-family: \"IBM Plex Sans\", sans-serif; font-size: 14px; line-height: 1.4; white-space: pre-wrap; }" +
      ".bot-msg.bot { align-self: flex-start; background: var(--surface-sunken, #F5F5F7); color: var(--ink, #1D1D1F); }" +
      ".bot-msg.user { align-self: flex-end; background: var(--accent, #C4501C); color: var(--accent-ink, #fff); }" +
      ".bot-draft-card {" +
      "  align-self: flex-start; max-width: 90%; background: var(--surface-sunken, #F5F5F7);" +
      "  border: 1px solid var(--line, #ddd); border-radius: var(--radius, 14px); padding: 10px 13px;" +
      "  font-family: \"IBM Plex Sans\", sans-serif; font-size: 13px; color: var(--ink, #1D1D1F);" +
      "}" +
      ".bot-draft-card b { font-family: \"Space Grotesk\", sans-serif; }" +
      ".bot-draft-table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 12.5px; }" +
      ".bot-draft-table th, .bot-draft-table td { padding: 4px 6px; text-align: right; border-bottom: 1px solid var(--line, #ddd); }" +
      ".bot-draft-table th:first-child, .bot-draft-table td:first-child { text-align: left; }" +
      ".bot-draft-table th { font-family: \"Space Grotesk\", sans-serif; color: var(--ink-muted, #6E6E73); font-weight: 600; }" +
      ".bot-draft-totals { margin-top: 6px; font-size: 12.5px; display: flex; flex-direction: column; gap: 2px; align-items: flex-end; }" +
      ".bot-draft-totals .bot-draft-net { font-family: \"Space Grotesk\", sans-serif; font-weight: 600; color: var(--ink, #1D1D1F); }" +
      ".bot-typing { align-self: flex-start; display: flex; gap: 4px; padding: 9px 13px; }" +
      ".bot-typing span { width: 6px; height: 6px; border-radius: 50%; background: var(--ink-muted, #999); opacity: .4; animation: bot-blink 1s infinite; }" +
      ".bot-typing span:nth-child(2) { animation-delay: .2s; } .bot-typing span:nth-child(3) { animation-delay: .4s; }" +
      "@keyframes bot-blink { 0%, 80%, 100% { opacity: .25; } 40% { opacity: 1; } }" +
      ".bot-panel-form { display: flex; gap: 8px; padding: 12px; border-top: 1px solid var(--line, #ddd); }" +
      ".bot-panel-input {" +
      "  flex: 1; border: 1px solid var(--line, #ddd); border-radius: var(--radius, 14px);" +
      "  padding: 9px 13px; font-family: \"IBM Plex Sans\", sans-serif; font-size: 14px;" +
      "  background: var(--bg, #fff); color: var(--ink, #1D1D1F);" +
      "}" +
      ".bot-panel-send {" +
      "  border: none; border-radius: var(--radius, 14px); padding: 0 16px;" +
      "  background: var(--accent, #C4501C); color: var(--accent-ink, #fff); font-weight: 600; cursor: pointer;" +
      "}" +
      ".bot-panel-send:disabled { opacity: .5; cursor: default; }" +
      "@media (max-width: 640px) {" +
      "  .bot-panel { right: 16px !important; left: 16px !important; bottom: 76px !important; top: auto !important; width: auto; }" +
      "}";
    document.head.appendChild(style);
  }

  function injectMarkup() {
    var launcher = document.createElement("div");
    launcher.className = "bot-launcher";
    launcher.innerHTML =
      '<button type="button" class="bot-fab" aria-label="Open the billing assistant" aria-haspopup="dialog">' +
      '<svg viewBox="0 0 24 24" aria-hidden="true">' +
      '<defs><linearGradient id="botFabGrad" x1="3" y1="1" x2="20" y2="22" gradientUnits="userSpaceOnUse">' +
      '<stop offset="0%" style="stop-color:var(--accent, #C4501C)"/>' +
      '<stop offset="100%" style="stop-color:color-mix(in srgb, var(--accent, #C4501C) 60%, black)"/>' +
      "</linearGradient></defs>" +
      '<line x1="12" y1="5.6" x2="12" y2="2.8" stroke="url(#botFabGrad)" stroke-width="1.4" stroke-linecap="round"/>' +
      '<circle cx="12" cy="2.1" r="1.15" fill="url(#botFabGrad)"/>' +
      '<path d="M12 5.7c4.42 0 8 3.34 8 7.45 0 4.3-3.7 7.75-8.2 7.75-1.66 0-3.2-.46-4.48-1.25.64.12 1.5-.24 1.44-1.08-.07-.86-1.08-1.13-2.06-.88-1.24.32-2.4-.38-2.4-1.63C4.3 8.9 7.75 5.7 12 5.7Z" fill="url(#botFabGrad)"/>' +
      '<circle cx="9.5" cy="11.9" r="1.15" fill="#fff"/>' +
      '<circle cx="14.5" cy="11.9" r="1.15" fill="#fff"/>' +
      "</svg>" +
      "</button>";
    document.body.appendChild(launcher);

    var panel = document.createElement("div");
    panel.className = "bot-panel";
    panel.setAttribute("role", "dialog");
    panel.setAttribute("aria-label", "Billing assistant chat");
    panel.innerHTML =
      '<div class="bot-panel-head"><span>NKMW Assistant</span><button type="button" class="bot-panel-close" aria-label="Close chat">&times;</button></div>' +
      '<div class="bot-panel-body"></div>' +
      '<form class="bot-panel-form"><input type="text" class="bot-panel-input" placeholder="Ask about buyers, invoices, or say \'bill Hella for 10x ABC123\'…" autocomplete="off" /><button type="submit" class="bot-panel-send">Send</button></form>';
    document.body.appendChild(panel);

    return { launcher: launcher, panel: panel };
  }

  function makeDraggable(el, onTap) {
    var btn = el.querySelector(".bot-fab");
    var dragging = false;
    var moved = false;
    var startX, startY, startLeft, startTop;

    function size() {
      var rect = el.getBoundingClientRect();
      return { w: rect.width || 44, h: rect.height || 44 };
    }

    function pinToEdge(edge, crossPx) {
      var s = size();
      el.style.left = el.style.right = el.style.top = el.style.bottom = "auto";
      if (edge === "left" || edge === "right") {
        var maxCrossV = Math.max(EDGE_MARGIN, window.innerHeight - s.h - EDGE_MARGIN);
        var top = Math.min(Math.max(crossPx, EDGE_MARGIN), maxCrossV);
        el.style[edge] = EDGE_MARGIN + "px";
        el.style.top = top + "px";
        return { edge: edge, cross: top };
      }
      var maxCrossH = Math.max(EDGE_MARGIN, window.innerWidth - s.w - EDGE_MARGIN);
      var left = Math.min(Math.max(crossPx, EDGE_MARGIN), maxCrossH);
      el.style[edge] = EDGE_MARGIN + "px";
      el.style.left = left + "px";
      return { edge: edge, cross: left };
    }

    function nearestEdge(rect) {
      var distances = {
        left: rect.left,
        right: window.innerWidth - rect.right,
        top: rect.top,
        bottom: window.innerHeight - rect.bottom
      };
      var winner = "right";
      var min = Infinity;
      for (var edge in distances) {
        if (distances[edge] < min) { min = distances[edge]; winner = edge; }
      }
      return winner;
    }

    function savePosition(pos) {
      try { localStorage.setItem(POSITION_KEY, JSON.stringify(pos)); } catch (err) { /* ignore */ }
    }

    function loadPosition() {
      try {
        var raw = localStorage.getItem(POSITION_KEY);
        if (!raw) return;
        var pos = JSON.parse(raw);
        if (pos && pos.edge) pinToEdge(pos.edge, pos.cross);
      } catch (err) { /* ignore */ }
    }

    btn.addEventListener("pointerdown", function (e) {
      if (e.button !== undefined && e.button !== 0) return;
      dragging = true;
      moved = false;
      var rect = el.getBoundingClientRect();
      startX = e.clientX; startY = e.clientY;
      startLeft = rect.left; startTop = rect.top;
      btn.setPointerCapture(e.pointerId);
    });

    btn.addEventListener("pointermove", function (e) {
      if (!dragging) return;
      var dx = e.clientX - startX;
      var dy = e.clientY - startY;
      if (!moved && Math.hypot(dx, dy) > DRAG_THRESHOLD) { moved = true; el.classList.add("is-dragging"); }
      if (!moved) return;
      var s = size();
      var left = Math.min(Math.max(startLeft + dx, 0), window.innerWidth - s.w);
      var top = Math.min(Math.max(startTop + dy, 0), window.innerHeight - s.h);
      el.style.right = el.style.bottom = "auto";
      el.style.left = left + "px";
      el.style.top = top + "px";
    });

    function endDrag() {
      if (!dragging) return;
      dragging = false;
      el.classList.remove("is-dragging");
      if (moved) {
        var rect = el.getBoundingClientRect();
        var edge = nearestEdge(rect);
        var cross = edge === "left" || edge === "right" ? rect.top : rect.left;
        savePosition(pinToEdge(edge, cross));
      } else {
        onTap();
      }
    }

    btn.addEventListener("pointerup", endDrag);
    btn.addEventListener("pointercancel", endDrag);

    window.addEventListener("resize", function () {
      try {
        var raw = localStorage.getItem(POSITION_KEY);
        if (!raw) return;
        var pos = JSON.parse(raw);
        if (pos && pos.edge) pinToEdge(pos.edge, pos.cross);
      } catch (err) { /* ignore */ }
    });

    loadPosition();
  }

  function initChat(functions, httpsCallable) {
    injectStyles();
    var els = injectMarkup();
    var body = els.panel.querySelector(".bot-panel-body");
    var form = els.panel.querySelector(".bot-panel-form");
    var input = els.panel.querySelector(".bot-panel-input");
    var sendBtn = els.panel.querySelector(".bot-panel-send");
    var closeBtn = els.panel.querySelector(".bot-panel-close");

    var state = loadState();
    var chatWithBot = httpsCallable(functions, "chatWithBot");

    function persist() {
      try { sessionStorage.setItem(STATE_KEY, JSON.stringify(state)); } catch (err) { /* ignore */ }
    }

    function positionPanel() {
      var rect = els.launcher.getBoundingClientRect();
      if (window.innerWidth <= 640) return; // CSS handles mobile layout
      var top = rect.top - 536 < 12 ? Math.min(rect.bottom + 10, window.innerHeight - 536) : rect.top - 530;
      var left = rect.left > window.innerWidth / 2 ? rect.right - 360 : rect.left;
      left = Math.min(Math.max(left, 12), window.innerWidth - 372);
      top = Math.max(top, 12);
      els.panel.style.top = top + "px";
      els.panel.style.left = left + "px";
    }

    function escapeHtml(str) {
      var div = document.createElement("div");
      div.textContent = str == null ? "" : String(str);
      return div.innerHTML;
    }

    function money(n) { return "₹" + Number(n || 0).toFixed(2); }

    function renderDraftCard(draft) {
      var rowsHtml = draft.items.map(function (it) {
        return "<tr><td>" + escapeHtml(it.partNo) + "</td><td>" + it.qty + "</td><td>" +
          money(it.rate) + "</td><td>" + money(it.amount) + "</td></tr>";
      }).join("");
      var card = document.createElement("div");
      card.className = "bot-draft-card";
      card.innerHTML =
        "<b>" + escapeHtml(draft.buyerName) + "</b>" +
        "<table class=\"bot-draft-table\"><thead><tr><th>Part</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead>" +
        "<tbody>" + rowsHtml + "</tbody></table>" +
        "<div class=\"bot-draft-totals\">" +
        "<span>Subtotal: " + money(draft.subtotal) + "</span>" +
        "<span>IGST: " + money(draft.igst) + "</span>" +
        "<span class=\"bot-draft-net\">Net: " + money(draft.net) + "</span>" +
        "</div>";
      body.appendChild(card);
    }

    function renderMessage(msg) {
      var div = document.createElement("div");
      div.className = "bot-msg " + (msg.role === "user" ? "user" : "bot");
      div.textContent = msg.text;
      body.appendChild(div);
      if (msg.draft) renderDraftCard(msg.draft);
    }

    function renderAll() {
      body.innerHTML = "";
      state.messages.forEach(renderMessage);
      body.scrollTop = body.scrollHeight;
    }

    function addMessage(role, text, draft) {
      var msg = { role: role, text: text, draft: draft || null };
      state.messages.push(msg);
      renderMessage(msg);
      body.scrollTop = body.scrollHeight;
      persist();
    }

    function setTyping(on) {
      var existing = body.querySelector(".bot-typing");
      if (on && !existing) {
        var t = document.createElement("div");
        t.className = "bot-typing";
        t.innerHTML = "<span></span><span></span><span></span>";
        body.appendChild(t);
        body.scrollTop = body.scrollHeight;
      } else if (!on && existing) {
        existing.remove();
      }
    }

    function openPanel() {
      state.open = true;
      persist();
      els.panel.classList.add("is-open");
      positionPanel();
      if (!state.messages.length) {
        addMessage("bot", "Hi! Ask me about buyers, rate cards, or past invoices — or say something like \"bill Hella for 10x ABC123\" and I'll draft it for you to review.");
      }
      input.focus();
    }

    function closePanel() {
      state.open = false;
      persist();
      els.panel.classList.remove("is-open");
    }

    function togglePanel() {
      if (state.open) closePanel(); else openPanel();
    }

    async function fillOnBillingPage(draft) {
      if (!window.NKMWBillingReady) return false;
      await window.NKMWBillingReady;
      await window.NKMWBillingBridge.fillDraft(draft);
      return true;
    }

    async function handleDraft(draft) {
      state.lastDraft = draft;
      persist();
      // The table rendered above is the preview -- only jump to billing.html
      // once the owner actually confirms (handleGenerateAction). If we're
      // already there, fill the form in place so it doubles as a live view.
      if (onBillingPage()) {
        await fillOnBillingPage(draft);
      }
    }

    async function handleGenerateAction() {
      if (onBillingPage() && window.NKMWBillingReady) {
        await window.NKMWBillingReady;
        window.NKMWBillingBridge.generate();
        state.lastDraft = null;
        persist();
      } else if (state.lastDraft) {
        try {
          sessionStorage.setItem(HANDOFF_KEY, JSON.stringify({ draft: state.lastDraft, action: "generate" }));
        } catch (err) { /* ignore */ }
        addMessage("bot", "Opening Billing to generate it…");
        setTimeout(function () { window.location.href = "billing.html"; }, 500);
      }
    }

    async function send(text) {
      addMessage("user", text);
      setTyping(true);
      sendBtn.disabled = true;
      try {
        var historyForApi = state.messages
          .slice(0, -1) // exclude the message we just added -- backend appends it itself
          .map(function (m) { return { role: m.role, text: m.text }; });
        var res = await chatWithBot({ message: text, history: historyForApi, pendingDraft: state.lastDraft });
        var data = res.data || {};
        addMessage("bot", data.reply || "…", data.draft);
        if (data.draft) await handleDraft(data.draft);
        if (data.action === "generate") await handleGenerateAction();
      } catch (err) {
        addMessage("bot", "Sorry, something went wrong" + (err && err.message ? ": " + err.message : ". Please try again."));
      } finally {
        setTyping(false);
        sendBtn.disabled = false;
      }
    }

    form.addEventListener("submit", function (e) {
      e.preventDefault();
      var text = input.value.trim();
      if (!text) return;
      input.value = "";
      send(text);
    });

    closeBtn.addEventListener("click", closePanel);
    window.addEventListener("resize", function () { if (state.open) positionPanel(); });

    renderAll();
    if (state.open) openPanel();

    // Cross-page handoff: a draft/generate request made on another page
    // navigates here, then resumes once the billing form is ready.
    if (onBillingPage()) {
      try {
        var raw = sessionStorage.getItem(HANDOFF_KEY);
        if (raw) {
          var handoff = JSON.parse(raw);
          sessionStorage.removeItem(HANDOFF_KEY);
          window.NKMWBillingReady.then(function () {
            return window.NKMWBillingBridge.fillDraft(handoff.draft);
          }).then(function () {
            if (handoff.action === "generate") window.NKMWBillingBridge.generate();
          });
        }
      } catch (err) { /* ignore */ }
    }

    return { launcher: els.launcher, toggle: togglePanel };
  }

  async function init() {
    try {
      var appModule = await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js");
      var authModule = await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js");
      var fsModule = await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js");
      var fnModule = await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-functions.js");

      var app = appModule.getApps().length ? appModule.getApps()[0] : appModule.initializeApp(firebaseConfig);
      var auth = authModule.getAuth(app);
      var db = fsModule.getFirestore(app);
      var functions = fnModule.getFunctions(app, "asia-south1");

      authModule.onAuthStateChanged(auth, function (user) {
        if (!user || !user.emailVerified) return;
        fsModule.getDoc(fsModule.doc(db, "profiles", user.uid)).then(function (snap) {
          var role = snap.exists() ? snap.data().role : null;
          if (role !== "master") return; // assistant is master-only for now

          var chat = initChat(functions, fnModule.httpsCallable);
          makeDraggable(chat.launcher, chat.toggle);
          requestAnimationFrame(function () { chat.launcher.classList.add("is-visible"); });
        }).catch(function (err) { console.error("bot-widget: role check failed", err); });
      });
    } catch (err) {
      console.error("bot-widget: init failed", err);
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
